### ISSUE TITLE
Mod Incompatibility

### ISSUE THREAD

**Issue by CatariPrime420** [Yokmp/Molten_Metals#1]
Mod is incompatible with One More Tier.
![OOOPS](https://user-images.githubusercontent.com/102835178/161349958-c1a3fc18-9bf2-4351-92e0-0791e13f79c2.png)

**Comment by CatariPrime420** [comment]
Ignore. Im an idiot and didnt read the Mod description. :/

**Comment by Yokmp** [comment]
Ok.
But you can contact the author of one-more-tier to include a check for hidden types / altered mining_result/next_upgrade:
[Molten_Metals/prototypes/vanilla/create.lua](https://github.com/Yokmp/Molten_Metals/blob/7cca01c332a34ae72c48ff1df446c5c08054f59c/prototypes/vanilla/create.lua#L11)
As you can see in the linked file above the electric furnace is flaged as hidden but the mining result is set as the modded machine. In your screenshot, the mining result is switched back to the vanilla furnace without changing the flag which then causes the error.

But thanks for your feedback anyways.
Let me know if anything didn't work as expected.

**Comment by CatariPrime420** [comment]
Hi! 
Yea i noticed the replace vanilla settings and unchecked those and it ran just fine with both. I also closed the ticket and provided that in the comments on the issue. My bad!
