### ISSUE TITLE
Proposed changes to balance, plates, energy use and pollution

### ISSUE THREAD

**Issue by VortiK** [Yokmp/Molten_Metals#2]
Hello, 

I've been playing with your mod and here's some tweaks I've made that I think would be good to add in your mod : 
- Boost Iron and Copper plate production from melting by ~33% (3 plates from 2 ore instead of 2 for 2 in vanilla furnace).
- Increase coal usage in smelters to be similar than vanilla furnace
- Increase energy usage accross the chain (smelters and casters) to be more than vanilla, but it's compensated as you get hot steam
- Increase pollution to be similar than vanilla furnace
- All in all you get more plates for less machines but a more complex setup

Vanilla

![image](https://user-images.githubusercontent.com/23299769/164967691-70f81131-929b-43f3-bc03-9f02798b4920.png)

Burner smelters and basic casters

![image](https://user-images.githubusercontent.com/23299769/164967411-7b7317c2-376b-4a44-ba3b-2574905af725.png)

Electric smelters and advanced casters

- No coal / fuel use and logistics, less machines, less pollution but much more energy usage and possibility to use modules

![image](https://user-images.githubusercontent.com/23299769/164967783-3d3cc1c8-876f-473a-ae79-afa56b9d8703.png)

With efficiency modules in smelters

![image](https://user-images.githubusercontent.com/23299769/164967881-3ebb8258-cb18-4b9c-825b-21c51d5c7d44.png)

Here's the patch file of the changes : 

```
From e266168868d56816b935957ca6e2d79483e9cfb0 Mon Sep 17 00:00:00 2001
From: Bruno NOGUER <bruno.noguer@gmail.com>
Date: Sun, 24 Apr 2022 10:22:37 +0200
Subject: [PATCH] boost iron and copper plate by melting, some balance more
 energy usage and pollution

---
 prototypes/vanilla/create.lua   |  4 ++--
 prototypes/vanilla/entities.lua | 12 ++++++------
 2 files changed, 8 insertions(+), 8 deletions(-)

diff --git a/prototypes/vanilla/create.lua b/prototypes/vanilla/create.lua
index c31ea8a..6f39608 100644
--- a/prototypes/vanilla/create.lua
+++ b/prototypes/vanilla/create.lua
@@ -52,9 +52,9 @@ end
 
 
 -- CASTING
-new_casting_recipe("copper-ore", "copper-ore", "copper-plate")
+new_casting_recipe("copper-ore", "copper-ore", "copper-plate", {2,3})
 new_casting_recipe("copper-ore", "copper-plate", "copper-cable")
-new_casting_recipe("iron-ore", "iron-ore", "iron-plate")
+new_casting_recipe("iron-ore", "iron-ore", "iron-plate", {2,3})
 new_casting_recipe("iron-ore", "iron-plate", "steel-plate", {1.6,2})
 new_casting_recipe("iron-ore", "iron-plate", "iron-gear-wheel", {1,1})
 new_casting_recipe("iron-ore", "iron-plate", "iron-stick", {1,1})
diff --git a/prototypes/vanilla/entities.lua b/prototypes/vanilla/entities.lua
index d744f5d..138adb2 100644
--- a/prototypes/vanilla/entities.lua
+++ b/prototypes/vanilla/entities.lua
@@ -49,12 +49,12 @@ data:extend({
     },
     source_inventory_size = 1,
     result_inventory_size = 1,
-		energy_usage = "270kW",
+		energy_usage = "1800kW",
     energy_source = {
       type = "burner",
       fuel_category = "chemical",
       effectivity = 1,
-      emissions_per_minute = 4,
+      emissions_per_minute = 40,
       fuel_inventory_size = 1,
       light_flicker =
       {
@@ -285,11 +285,11 @@ data:extend({
       fade_in_ticks = 4,
       fade_out_ticks = 20
     },
-    energy_usage = "525kW",
+    energy_usage = "3600kW",
 		energy_source = {
 			type = "electric",
 			usage_priority = "secondary-input",
-      emissions_per_minute = 1,
+			emissions_per_minute = 20,
 			smoke =	{
 				{
 					name = "smoke",
@@ -540,7 +540,7 @@ data:extend({
     energy_source = {
       type = "electric",
       usage_priority = "secondary-input",
-      emissions_per_minute = 3,
+      emissions_per_minute = 8,
     },
     animation = make_4way_animation_from_spritesheet({
       layers = {
@@ -873,7 +873,7 @@ data:extend({
     energy_source = {
       type = "electric",
       usage_priority = "secondary-input",
-      emissions_per_minute = 2,
+      emissions_per_minute = 10,
     },
     animation = make_4way_animation_from_spritesheet({
       layers = {
-- 
2.16.0.windows.2
```

**Comment by Yokmp** [comment]
Im currently testing your changes. 
Also, i made several changes to the steam temperature. I've read multiple sites of wikipedia on various metals and their melting/boiling points and then forgot about it ^^
After my recent rediscovery i've changed the steam temperature to 
`math.max(math.min((temperature.max - temperature.min)/2, 1000), 100)`
which

- clamps the temp between 100 and 1000
- results in a good variation in temperature 
- forces you to think about which steam to mix

EG the melting points of iron (1500) and lead (320) are so different that mixing the resulting steam would drastically decrease its temperture and so the potetial energy production.

The formula isn't final but represents the idea behind it.

**Comment by VortiK** [comment]
Hello, 

Thanks for your consideration on the changes.

About steam, I don't think it's possible to mix fluids with different temperatures,. Also Steam Engine are best used with 165° steam and turbine with 500° steam. Not sure if it's worth fidling with this, handeling steam as a by product is a already enough or a downside to the casting system imo.

**Comment by Yokmp** [comment]
It seems that max_temp in generators describes their max power output rather than their max usable temp. So this doesn't rly matter.
I also made it so that the steam temp is based on the meltin point of the ore but just to be save i've adde an option to toggle this so you can choose between 500°C static or let it calculate the temp. As long as you don't mix steam from tin and steam from aluminium it shouldn't matter. The only thing where this comes into play (or of which i can think of atm) is UPS in lategame when temps mix and have to be calcualted. But then again, there is an option.
